---
- name: ENABLE WINRM
  connection: local
  gather_facts: no
  #  hosts: all
  hosts: localhost
  vars:
    my_resource_group: myResourceGroup
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=
    my_subscription_id: 003f4a25-c561-4987-9c2e-d3ad6cdfe9c5
    my_client_id: 156dd41a-2d31-4bb6-8fea-84102761bbbc
    my_secret: xHdFVeH1Org9h7PH2Bpx8bSi4qg68cq1KSdCt26qKUM=
    my_tenant: 35420ee2-8fb8-4f97-9823-9855f934397a
    my_vm_name: myvm5514
    my_admin_password: Redhat179917
  tasks:
  - name: CREATE AZURE VM EXTENSION TO ENABLE HTTPS WINRM LISTENER
    azure_rm_virtualmachine_extension:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      name: winrm-extension
      resource_group: "{{ my_resource_group }}"
      virtual_machine_name: "{{ my_vm_name }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
      auto_upgrade_minor_version: true

  - name: WAIT FOR WINRM TO GO ONLINE
    wait_for:
      port: 5986
      host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
      timeout: 600
